Changed default 'squeak' from GemTools-3.0 to GemTools-MagLev. Removed 'gemx' as it no longer exists.

diff --git a/bin/maglev b/bin/maglev
--- a/bin/maglev
+++ b/bin/maglev
@@ -31,6 +31,11 @@ maglev help           - Display this text
 ENDHELP
 }
 
+# Detect operating system
+OS=`uname -s`
+[ $OS = "Darwin" ] && OS="MacOSX"
+[ $OS = "SunOS" ] && [ "`uname -m`" = "i86pc" ] && OS="Solaris-x86"
+
 # Environment variable settings
 if [ -z "$MAGLEV_HOME" ]; then
   if [ -x $PWD/gemstone/bin/startstone ]; then
@@ -285,12 +290,31 @@ destroy() {
 
 squeak() {
   # If you use Squeak for development and debugging
-  if [ -e /Applications/GemTools-3.0.app ]; then
-      open /Applications/GemTools-3.0.app
-  else
-      echo "The GemTools application used by the 'squeak' command was not found on your system"
-      echo "To fix this, correct the 'squeak' command in the maglev script"
-  fi
+  case "$OS" in
+      MacOSX)
+      if [ -e /Applications/GemTools-MagLev.app ]; then
+          open /Applications/GemTools-MagLev.app
+      else
+          echo "[Error] Cannot open /Applications/GemTools-MagLev.app"
+          echo "File does not exist."
+          exit 1
+      fi
+      ;;
+      Linux)
+      if [ -e $MAGLEV_HOME/../GemTools-MagLev.app/GemTools.sh ]; then
+          bash $MAGLEV_HOME/../GemTools-MagLev.app/GemTools.sh &
+      else
+          echo "[Error] Cannot open \$MAGLEV_HOME/../GemTools-MagLev.app/GemTools.sh"
+          echo "File does not exist."
+          exit 1
+      fi
+      ;;
+      *)
+      echo "[Error] "maglev squeak" only works on a Linux or Mac OS X"
+      echo "The result from \"uname -sm\" is \"`uname -sm`\""
+      exit 1
+      ;;
+  esac
 }
 
 startvsd() {
@@ -302,17 +326,6 @@ mri() {
   export DYLD_LIBRARY_PATH=$GEMSTONE/lib32
   irb -I $MAGLEV_HOME/gci -rgci
 }
-
-gemx() {
-  # If you use Squeak for development and debugging
-  if [ -e /Applications/GemX.app ]; then
-      open /Applications/GemX.app
-  else
-      echo "The application used by the 'gemx' command was not found on your system"
-      echo "To fix this, correct the 'gemx' command in the maglev script"
-  fi
-}
-
 
 # See what we were asked to do
 case "$1" in
@@ -389,9 +402,6 @@ case "$1" in
         ;;
   mri)
         mri
-        ;;
-  gemx)
-        gemx
         ;;
   force-reload)
         stopserver
