try to be clever about finding MAGLEV_HOME

diff --git a/bin/maglev b/bin/maglev
--- a/bin/maglev
+++ b/bin/maglev
@@ -44,9 +44,16 @@ if [ -z "$MAGLEV_HOME" ]; then
     # echo "using $PWD as MAGLEV_HOME"
     export MAGLEV_HOME=$PWD
   else
-    echo "$COMMAND: [Error] $PWD is not a valid MAGLEV_HOME directory"
-    echo "To fix this, set a valid MAGLEV_HOME in your .bashrc"
-    exit 1
+    echo "$COMMAND: [Warning] \$MAGLEV_HOME is not set."
+    tree=$(cd `dirname "$0"/` ; cd .. ; pwd)
+    if [ -d "${tree}/gemstone" ]; then
+      export MAGLEV_HOME="${tree}"
+      echo "Assuming ${MAGLEV_HOME}"
+    else
+      echo "$COMMAND: [Error] Neither $PWD nor $tree are a valid MAGLEV_HOME directory"
+      echo "To fix this, set a valid MAGLEV_HOME in your .bashrc"
+      exit 1
+    fi
   fi
 fi
 # Set environment variables unless they already exist
diff --git a/bin/maglev-ruby b/bin/maglev-ruby
--- a/bin/maglev-ruby
+++ b/bin/maglev-ruby
@@ -278,9 +278,20 @@ parseArgs $RUBYOPT
 
 # Make sure MAGLEV_HOME is set
 if [ -z "${MAGLEV_HOME}" ]; then
-    echo "$COMMAND: [Error] \$MAGLEV_HOME is not set."
-    echo "To fix this, set a valid MAGLEV_HOME in your .bashrc"
-    exit 1
+  tree=$(cd `dirname "$0"/` ; cd .. ; pwd)
+
+  if [ -d "${tree}/gemstone" ]; then
+    export MAGLEV_HOME="${tree}"
+    [ -z "$STONENAME" ] && [ -z "$GEMSTONE_GLOBAL_DIR" ] && export GEMSTONE_GLOBAL_DIR=$MAGLEV_HOME
+    if [ -n "$debugFlag" ]; then
+      echo "$COMMAND: [Warning] \$MAGLEV_HOME is not set."
+      echo "Assuming ${MAGLEV_HOME}"
+    fi
+  else
+      echo "$COMMAND: [Error] \$MAGLEV_HOME is not set."
+      echo "To fix this, set a valid MAGLEV_HOME, e.g. in your .bashrc"
+      exit 1
+  fi
 fi
 
 # Make sure GEMSTONE is set
