Don't set GEMSTONE_EXE_CONF env variable if it's not set. That's too big a hammer.

diff --git a/bin/maglev-ruby b/bin/maglev-ruby
--- a/bin/maglev-ruby
+++ b/bin/maglev-ruby
@@ -6,16 +6,14 @@ COMMAND="`basename $0`"
 usage()
 {
 cat << EOF
-Usage: $COMMAND [options] [--] filename [script-args]
+Usage: $COMMAND [switches] [--] [programfile] [arguments]
 
     Execute a Ruby file with MagLev
-
-    Currently, the filename argument is required.
 
 OPTIONS:
    --copyright    Print copyright and exit
    -d, --debug    Set debugging flags. Allows topaz debugging.
-   -e <command>   Execute command.  May pass multiple -e
+   -e 'command'   Execute command. Several -e's allowed. Omit [programfile]
    -G             Use /opt/gemstone instead of MAGLEV_HOME for locks and logs
    -h, --help     Show this message and exit
    -I <path>      Add <path> to \$LOAD_PATH
@@ -25,25 +23,25 @@ OPTIONS:
                     traceLoad     Trace loading of ruby files
                     logSexp       Print sexpressions as they are parsed
                     noRlwrap      invoke topaz without rlwrap
-   --             End of MagLev parameters.  The next parameter is the script
-                  name, then script parameters follow.
-   --stone <name> Run script connecting to the named stone
+   --             End of MagLev parameters.  The next parameter is the programfile,
+                  then any programfile arguments follow.
+   --stone <name> Run programfile connecting to the named stone
    -v, --verbose  Print version number, then turn on verbose mode
    --version      Print version number and exit
 
-MagLev will also read the MAGLEV_OPTS environment variable for options.
+Options can be set in the MAGLEV_OPTS environment variable as well as on the command line.
 EOF
 }
 
 # The environment variable STONENAME is for use by internal GemStone developers and QA
 # who start the stone manually instead of using "maglev start" or "rake maglev:start"
-# If STONENAME is set, GEMSTONE_GLOBAL_DIR, GEMSTONE_SYS_CONF, and GEMSTONE_EXE_CONF
-# will not be set -- even if they are undefined.
+# If STONENAME is set, GEMSTONE_GLOBAL_DIR and GEMSTONE_SYS_CONF will not be set 
+# -- even if they are undefined.
 #
-# Existing GEMSTONE_GLOBAL_DIR, GEMSTONE_SYS_CONF env variables will never be overridden.
-# If GEMSTONE_GLOBAL_DIR is not defined, it will be set to $MAGLEV_HOME. 
-# If the _CONF environment variables are not defined, they will be set based on
-# the --stone parameter, otherwise defaulted to etc/system.conf.
+# Existing GEMSTONE_GLOBAL_DIR and GEMSTONE_SYS_CONF env variables will never be
+# overridden. If GEMSTONE_GLOBAL_DIR is not defined, it will be set to $MAGLEV_HOME. 
+# If the GEMSTONE_SYS_CONF environment variables is not defined, it will be set
+# based on the --stone parameter, otherwise defaulted to etc/system.conf.
 
 # Prepend the maglev options onto the passed parameters so we can parse
 # them all the same in one pass
@@ -82,17 +80,6 @@ useRlwrap=1
 while [ $# -gt 0 ]
 do
     case "$1" in
-        --stone)
-            stone=$2
-            # Don't override any existing magic ENV variables
-            [ -z "$GEMSTONE_SYS_CONF" ] && export GEMSTONE_SYS_CONF=$MAGLEV_HOME/etc/conf.d/${stone}.conf
-            [ -z "$GEMSTONE_EXE_CONF" ] && export GEMSTONE_EXE_CONF=$MAGLEV_HOME/etc/conf.d/${stone}.conf
-            if [ ! -f $GEMSTONE_SYS_CONF ]; then
-                echo "Can't find configuration file $GEMSTONE_SYS_CONF"
-              exit 2
-            fi
-            shift
-            ;;
         --copyright)
             echo "maglev - Copyright (C) 2008-2009 GemStone Systems, Inc."
             exit
@@ -129,6 +116,16 @@ do
             else
                 maglev_options="$maglev_options ${sub_opt}"
             fi
+            ;;
+        --stone)
+            stone=$2
+            # Don't override any existing magic ENV variables
+            [ -z "$GEMSTONE_SYS_CONF" ] && export GEMSTONE_SYS_CONF=$MAGLEV_HOME/etc/conf.d/${stone}.conf
+            if [ ! -f $GEMSTONE_SYS_CONF ]; then
+                echo "Can't find configuration file $GEMSTONE_SYS_CONF"
+              exit 2
+            fi
+            shift
             ;;
         -v|--verbose)
             grep ^maglev $MAGLEV_HOME/version.txt
@@ -167,7 +164,6 @@ done
 if [ -z "$STONENAME" ]; then
 	stone=maglev
     [ -z "$GEMSTONE_SYS_CONF" ] && export GEMSTONE_SYS_CONF=$MAGLEV_HOME/etc/system.conf
-    [ -z "$GEMSTONE_EXE_CONF" ] && export GEMSTONE_EXE_CONF=$MAGLEV_HOME/etc/system.conf
 else
     # $STONENAME was set -- don't change anything
 	stone=$STONENAME
@@ -272,13 +268,14 @@ exitifnoerror
 EOFC
 fi
 
-# echo "GEMSTONE_SYS_CONF = $GEMSTONE_SYS_CONF"
-# echo "GEMSTONE_EXE_CONF = $GEMSTONE_EXE_CONF"
-# echo "GEMSTONE_GLOBAL_DIR = $GEMSTONE_GLOBAL_DIR"
-
 TOPAZ_CMD="$GEMSTONE/bin/topaz -l -q -I $dbscript "
 # If debugging, don't use -q with topaz
 [ $debug -ne 0 ] && TOPAZ_CMD="$GEMSTONE/bin/topaz -l -I $dbscript "
+
+# echo "GEMSTONE_GLOBAL_DIR = $GEMSTONE_GLOBAL_DIR"
+# echo "GEMSTONE_SYS_CONF = $GEMSTONE_SYS_CONF"
+# echo "GEMSTONE_EXE_CONF = $GEMSTONE_EXE_CONF"
+# echo "TOPAZ_CMD = $TOPAZ_CMD"
 
 # note that /usr/bin/which on Solaris always produces $?==0, so be careful
 #  about how you test result of which.
